### ISSUE TITLE
Web Connector does not decode the access_token!

### ISSUE THREAD

**Issue by minemeraj** [rwth-acis/Web-Client-Template-Project#1]
The line 38 of file [serviceAPI.js](https://github.com/rwth-acis/Web-Client-Template-Project/blob/master/JS/ServiceAPI/serviceAPI.js) should be like this:

`return String(this.accessToken);`

Because, the [WebConnectorRequestHandler](https://github.com/rwth-acis/LAS2peer-WebConnector/blob/master/src/main/java/i5/las2peer/webConnector/WebConnectorRequestHandler.java) doesn't decode the access_token. So, Invalid access_token error occurs.

**Comment by pedela** [comment]
Please don't use this project anymore. It is deprecated. The line you are referring to uses base64 username + credentials encoding, not OIDC. Take a look here: https://github.com/rwth-acis/LAS2peer-Template-Project in the frontend folder for further hints on how to use a las2peer frontend.:-)
